title: "Adel B."
author: "adel"
description: "Made with Jekyll"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", icon: home}
  - {file: "code.md", icon: code}
  - {file: "album.md", icon: music}
  - {file: "etc.md", icon: asterisk}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: About, icon: address-card, file: "about.md"}
  - {title: Mail, icon: envelope, url: "mailto:bordbariadel@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/adelbordbari"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-paginate-v2

pagination:
  enabled: true

### CUSTOM
collections:
  code:
    output: true
  album:
    output: true
  etc:
    output: true
  
permalink: /:collection/:path/
